Updates robin-hood-hashing (#3151)
* Updates robin-hood-hashing

due to compile error

```
FAILED: test/CMakeFiles/idtable.dir/idtable.cc.o
sccache /usr/bin/c++ -DAUTO_DOWNLOAD=0 -DBOOST_ALL_NO_LIB -DBOOST_NO_CXX11_SCOPED_ENUMS -DCURL_STATICLIB -DDATA_TOOLS -DHAS_REMOTE_API=
0 -DHAVE_HTTP -DVALHALLA_BUILD_DIR="/home/anders/Documents/Programming/mapbox/valhalla/build/" -DVALHALLA_SOURCE_DIR="/home/anders/D
ocuments/Programming/mapbox/valhalla/" -I../test -I../test/gurka -I../third_party/protozero/include -I../third_party/libosmium/include
 -I../third_party/microtar/src -I../ -I../valhalla -Isrc -Isrc/valhalla -I../third_party/rapidjson/include -I../third_party/date/includ
e -I../third_party/robin-hood-hashing/src/include -isystem /usr/include/luajit-2.0 -isystem ../third_party/googletest/googletest/includ
e -isystem ../third_party/googletest/googletest -isystem ../third_party/googletest/googlemock/include -isystem ../third_party/googletes
t/googlemock -fdiagnostics-color=auto  -g -mfpmath=sse -msse2 -pthread -std=gnu++14 -MD -MT test/CMakeFiles/idtable.dir/idtable.cc.o -M
F test/CMakeFiles/idtable.dir/idtable.cc.o.d -o test/CMakeFiles/idtable.dir/idtable.cc.o -c ../test/idtable.cc
In file included from ../test/../src/mjolnir/idtable.h:10,
                 from ../test/idtable.cc:1:
../third_party/robin-hood-hashing/src/include/robin_hood.h: In member function ‘size_t robin_hood::detail::Table<IsFlat, MaxLoadFactor1
00, Key, T, Hash, KeyEqual>::calcMaxNumElementsAllowed(size_t) const’:
../third_party/robin-hood-hashing/src/include/robin_hood.h:1875:52: error: ‘numeric_limits’ is not a member of ‘std’
 1875 |         if (ROBIN_HOOD_LIKELY(maxElements <= (std::numeric_limits<size_t>::max)() / 100)) {
      |                                                    ^~~~~~~~~~~~~~
../third_party/robin-hood-hashing/src/include/robin_hood.h:174:59: note: in definition of macro ‘ROBIN_HOOD_LIKELY’
  174 | #    define ROBIN_HOOD_LIKELY(condition) __builtin_expect(condition, 1)
      |                                                           ^~~~~~~~~
../third_party/robin-hood-hashing/src/include/robin_hood.h:1875:73: error: expected primary-expression before ‘>’ token
 1875 |         if (ROBIN_HOOD_LIKELY(maxElements <= (std::numeric_limits<size_t>::max)() / 100)) {
      |                                                                         ^
../third_party/robin-hood-hashing/src/include/robin_hood.h:174:59: note: in definition of macro ‘ROBIN_HOOD_LIKELY’
  174 | #    define ROBIN_HOOD_LIKELY(condition) __builtin_expect(condition, 1)
      |                                                           ^~~~~~~~~
../third_party/robin-hood-hashing/src/include/robin_hood.h:1875:76: error: ‘::max’ has not been declared; did you mean ‘std::max’?
 1875 |         if (ROBIN_HOOD_LIKELY(maxElements <= (std::numeric_limits<size_t>::max)() / 100)) {
      |                                                                            ^~~
../third_party/robin-hood-hashing/src/include/robin_hood.h:174:59: note: in definition of macro ‘ROBIN_HOOD_LIKELY’
  174 | #    define ROBIN_HOOD_LIKELY(condition) __builtin_expect(condition, 1)
      |                                                           ^~~~~~~~~
In file included from /usr/include/c++/11.1.0/algorithm:62,
                 from ../test/../src/mjolnir/idtable.h:4,
                 from ../test/idtable.cc:1:
/usr/include/c++/11.1.0/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
[197/825] Building CXX object test/CMakeFiles/reach.dir/reach.cc.o
In file included from /usr/include/boost/bind.hpp:30,
                 from /usr/include/boost/property_tree/json_parser/detail/parser.hpp:7,
                 from /usr/include/boost/property_tree/json_parser/detail/read.hpp:13,
                 from /usr/include/boost/property_tree/json_parser.hpp:16,
                 from ../test/gurka/gurka.h:29,
                 from ../test/reach.cc:1:
/usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global n
amespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDER
S to retain the current behavior.’
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
```

on clang version 11.1.0

* changelog

* Updates google benchmark to v1.5.5

due to compile error on clang 12.0 on Linux

```
FAILED: benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o
sccache /usr/bin/c++ -DBOOST_NO_CXX11_SCOPED_ENUMS -DDATA_TOOLS -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -DHAVE_STEADY_CLOCK -Dbenchmark_EXPORTS -I../third_party/benchmark/include -I../third_party/benchmark/src -I../third_party/benchmark/src/../include -fdiagnostics-color=auto   -std=c++11  -Wall  -Wextra  -Wshadow  -fstrict-aliasing  -Wno-deprecated-declarations  -Wstrict-aliasing -O2 -g -DNDEBUG  -Werror  -Wno-deprecated -fPIC -std=gnu++14 -MD -MT benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o -MF benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o.d -o benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o -c ../third_party/benchmark/src/benchmark_register.cc
In file included from ../third_party/benchmark/src/benchmark_register.cc:15:
../third_party/benchmark/src/benchmark_register.h: In function ‘typename std::vector<T>::iterator benchmark::internal::AddPowers(std::vector<T>*, T, T, int)’:
../third_party/benchmark/src/benchmark_register.h:22:30: error: ‘numeric_limits’ is not a member of ‘std’
   22 |   static const T kmax = std::numeric_limits<T>::max();
      |                              ^~~~~~~~~~~~~~
../third_party/benchmark/src/benchmark_register.h:22:46: error: expected primary-expression before ‘>’ token
   22 |   static const T kmax = std::numeric_limits<T>::max();
      |                                              ^
../third_party/benchmark/src/benchmark_register.h:22:49: error: ‘::max’ has not been declared; did you mean ‘std::max’?
   22 |   static const T kmax = std::numeric_limits<T>::max();
      |                                                 ^~~
      |                                                 std::max
In file included from /usr/include/c++/11.1.0/algorithm:62,
                 from ../third_party/benchmark/include/benchmark/benchmark.h:172,
                 from ../third_party/benchmark/src/internal_macros.h:4,
                 from ../third_party/benchmark/src/check.h:8,
                 from ../third_party/benchmark/src/benchmark_register.h:6,
                 from ../third_party/benchmark/src/benchmark_register.cc:15:
/usr/include/c++/11.1.0/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
```